server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: nacos_service_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai&serverTimezone=GMT%2B8
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

seata:
  enabled: true
  application-id: seata-order-service
  tx-service-group: nacos_consumer_tx_group
  #使用自动代理数据源时，XA模式
  #data-source-proxy-mode: XA
  # 关闭seata-spring-boot-starter的数据源自动代理
  enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      namespace: fb31c4c2-29ac-456c-b9d6-36321baceae4
      server-addr: "127.0.0.1:8848"
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      server-addr: "127.0.0.1:8848"
      namespace: fb31c4c2-29ac-456c-b9d6-36321baceae4
      cluster: default
      application: seata-server
      username: nacos
      password: nacos
  client:
    tm:
      rollback-retry-count: 3